### ISSUE TITLE
单独调用proxy 没有错误

### ISSUE THREAD

**Issue by smirkcat** [yincongcyincong/proxy-web#2]
使用这个调用时出现run service [tcp] fail, ERR:tcp servcie fail, ERR: listen tcp: lookup ": no such host

**Comment by yincongcyincong** [comment]
我不明白具体什么意思。。。

**Comment by smirkcat** [comment]
测试了 是加了引号的原因

**Comment by yincongcyincong** [comment]
ok

**Comment by smirkcat** [comment]
就是参数有引号包裹的话 就会出现各种错误  命令行是没有问题
