### ISSUE TITLE
多用户登录和在linux下后台运行

### ISSUE THREAD

**Issue by luomoxu** [yincongcyincong/proxy-web#3]
没有退出登录功能，希望添加个多用户登录的支持
还有就是linux下支持后台运行

**Comment by yincongcyincong** [comment]
多用户登录暂时不支持（主要是并发问题这个要处理一下），linux下可以加 & 进行后台运行，退出登录功能已经有了，最近会发一版

**Comment by yincongcyincong** [comment]
新版已发，可以用新的，有退出登录，但是还是没有多人同时登录
