### ISSUE TITLE
端口转发项过多 会导致无法启动

### ISSUE THREAD

**Issue by bhzhu203** [yincongcyincong/proxy-web#5]
./proxy-web  
tcp -p "192.168.2.111:2231" -T tcp -P "10.0.3.3:2231"
tcp -p "192.168.2.111:49155" -T tcp -P "172.17.0.40:443"
2018/08/22 13:10:02 WS Log Server on [::]:8822
2018/08/22 13:10:02 tail server on [::]:8822
tcp -p "192.168.2.111:2235" -T tcp -P "192.168.2.252:80"
proxy-web: 127.0.0.1::48080
tcp -p "192.168.2.111:6375" -T tcp -P "10.0.3.3:6375"
tcp -p "192.168.2.111:2127" -T tcp -P "172.17.0.52:2121"
tcp -p "192.168.2.111:2224" -T tcp -P "10.0.3.3:2224"
fatal error: concurrent map iteration and map write
tcp -p "192.168.2.111:9999" -T tcp -P "10.0.3.3:9000"

goroutine 22 [running]:
runtime.throw(0xadf807, 0x26)
	/usr/lib/golang/src/runtime/panic.go:605 +0x95 fp=0xc4202418b0 sp=0xc420241890 pc=0x42d565
runtime.mapiternext(0xc4202419a0)
	/usr/lib/golang/src/runtime/hashmap.go:778 +0x6f1 fp=0xc420241948 sp=0xc4202418b0 pc=0x40b731
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*flagGroup).init(0xc420314000, 0x0, 0x0, 0x0, 0x448d00)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/flags.go:41 +0xad fp=0xc420241a10 sp=0xc420241948 pc=0x93c6ed
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).init(0xc42030e000, 0x60020241c38, 0x10)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:330 +0xb6 fp=0xc420241b50 sp=0xc420241a10 pc=0x935496
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).parseContext(0xc42030e000, 0xc420134300, 0xc420134380, 0x7, 0x8, 0xc400000031, 0x0, 0x31)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:169 +0x2f fp=0xc420241bb0 sp=0xc420241b50 pc=0x9340df
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).ParseContext(0xc42030e000, 0xc420134380, 0x7, 0x8, 0xe, 0xc42011cca0, 0xc42011cc00)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:165 +0x4e fp=0xc420241c00 sp=0xc420241bb0 pc=0x93407e
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc42030e000, 0xc420134380, 0x7, 0x8, 0xc4201624e7, 0xd, 0x4, 0x8)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:185 +0x67 fp=0xc420241cc8 sp=0xc420241c00 pc=0x9343c7
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.StartWithLog(0xc420142990, 0xd, 0xc4201624c0, 0x35, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:293 +0x1639b fp=0xc420245f10 sp=0xc420241cc8 pc=0x96d87b
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.Start(0xc420142990, 0xd, 0xc4201624c0, 0x35, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:48 +0x5b fp=0xc420245f60 sp=0xc420245f10 pc=0x9574bb
proxy-web/server.autoRunCommand(0xc420142990, 0xd, 0xc4201624c0, 0x35)
	/root/go/src/proxy-web/server/server.go:100 +0xc1 fp=0xc420245fc0 sp=0xc420245f60 pc=0x991691
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420245fc8 sp=0xc420245fc0 pc=0x45dc81
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fc1e93f4eb0, 0x72, 0xffffffffffffffff)
	/usr/lib/golang/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420146698, 0x72, 0xc420061b00, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420146698, 0xffffffffffffff00, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420146680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc420146680, 0x7fc1e9450d90, 0x0, 0xaf1618)
	/usr/lib/golang/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42013e988, 0xc420061cf8, 0x412c88, 0x30)
	/usr/lib/golang/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42013e988, 0xc4201e5380, 0xc4201e5380, 0xa110c0)
	/usr/lib/golang/src/net/tcpsock.go:234 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42013e988, 0xc4200160e0, 0xa110c0, 0xeadee0, 0xab35c0)
	/usr/lib/golang/src/net/http/server.go:3120 +0x2f
net/http.(*Server).Serve(0xc4201d1ee0, 0xe60900, 0xc42013e988, 0x0, 0x0)
	/usr/lib/golang/src/net/http/server.go:2695 +0x1b2
net/http.(*Server).ListenAndServe(0xc4201d1ee0, 0xc4201d1ee0, 0x0)
	/usr/lib/golang/src/net/http/server.go:2636 +0xa9
net/http.ListenAndServe(0xc4201439a7, 0x6, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/http/server.go:2882 +0x7f
proxy-web/server.StartServer()
	/root/go/src/proxy-web/server/server.go:64 +0x5a1
main.main()
	/root/go/src/proxy-web/main.go:26 +0x20

goroutine 19 [select]:
proxy-web/vendor/github.com/xtaci/kcp-go.(*updateHeap).updateTask(0xebe9c0)
	/root/go/src/proxy-web/vendor/github.com/xtaci/kcp-go/updater.go:81 +0x2c2
created by proxy-web/vendor/github.com/xtaci/kcp-go.init.2
	/root/go/src/proxy-web/vendor/github.com/xtaci/kcp-go/updater.go:13 +0x74

goroutine 20 [runnable]:
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*parserMixin).String(...)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/flags.go:32
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.StartWithLog(0xc420142860, 0xd, 0xc420162440, 0x38, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:219 +0xe749
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.Start(0xc420142860, 0xd, 0xc420162440, 0x38, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:48 +0x5b
proxy-web/server.autoRunCommand(0xc420142860, 0xd, 0xc420162440, 0x38)
	/root/go/src/proxy-web/server/server.go:100 +0xc1
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 21 [runnable]:
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.StartWithLog(0xc420142910, 0xd, 0xc420162480, 0x38, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:138 +0x7120
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.Start(0xc420142910, 0xd, 0xc420162480, 0x38, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:48 +0x5b
proxy-web/server.autoRunCommand(0xc420142910, 0xd, 0xc420162480, 0x38)
	/root/go/src/proxy-web/server/server.go:100 +0xc1
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 23 [runnable]:
proxy-web/server.autoRunCommand(0xc420142a00, 0xd, 0xc420162540, 0x33)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 24 [runnable]:
proxy-web/server.autoRunCommand(0xc420142a80, 0xd, 0xc420162580, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 25 [runnable]:
proxy-web/server.autoRunCommand(0xc420142af0, 0xd, 0xc4201625c0, 0x39)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 26 [runnable]:
proxy-web/server.autoRunCommand(0xc420142b70, 0xd, 0xc420162600, 0x39)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 27 [runnable]:
proxy-web/server.autoRunCommand(0xc420142be0, 0xd, 0xc420162640, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 28 [runnable]:
proxy-web/server.autoRunCommand(0xc420142c60, 0xd, 0xc420162680, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 29 [runnable]:
proxy-web/server.autoRunCommand(0xc420142ce0, 0xd, 0xc4201626c0, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 30 [runnable]:
proxy-web/server.autoRunCommand(0xc420142d60, 0xd, 0xc420162700, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 31 [runnable]:
proxy-web/server.autoRunCommand(0xc420142de0, 0xd, 0xc420162740, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 32 [runnable]:
proxy-web/server.autoRunCommand(0xc420142e60, 0xd, 0xc420162780, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 33 [runnable]:
proxy-web/server.autoRunCommand(0xc420142ed0, 0xd, 0xc4201627c0, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 34 [runnable]:
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*parserMixin).String(...)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/flags.go:33
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.StartWithLog(0xc420142f50, 0xd, 0xc420162800, 0x35, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:79 +0x291db
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.Start(0xc420142f50, 0xd, 0xc420162800, 0x35, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:48 +0x5b
proxy-web/server.autoRunCommand(0xc420142f50, 0xd, 0xc420162800, 0x35)
	/root/go/src/proxy-web/server/server.go:100 +0xc1
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 35 [runnable]:
proxy-web/server.autoRunCommand(0xc420142fd0, 0xd, 0xc420162840, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 36 [runnable]:
proxy-web/server.autoRunCommand(0xc420143040, 0xd, 0xc420162880, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 37 [runnable]:
proxy-web/server.autoRunCommand(0xc4201430b0, 0xd, 0xc4201628c0, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 38 [runnable]:
proxy-web/server.autoRunCommand(0xc4201431b0, 0xd, 0xc420162940, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 39 [runnable]:
proxy-web/server.autoRunCommand(0xc420143220, 0xd, 0xc420162980, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 40 [runnable]:
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.StartWithLog(0xc4201432a0, 0xd, 0xc4201629c0, 0x38, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:60 +0x294df
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.Start(0xc4201432a0, 0xd, 0xc4201629c0, 0x38, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:48 +0x5b
proxy-web/server.autoRunCommand(0xc4201432a0, 0xd, 0xc4201629c0, 0x38)
	/root/go/src/proxy-web/server/server.go:100 +0xc1
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 41 [runnable]:
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*flagGroup).checkDuplicates(0xc4203800f0, 0x0, 0xc420388538)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/flags.go:68 +0xe4
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*flagGroup).init(0xc4203800f0, 0x0, 0x0, 0xc42038e4e8, 0xc420380090)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/flags.go:38 +0x40
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*CmdClause).init(0xc420398000, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/cmd.go:256 +0x57
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).init(0xc42037e000, 0x60020379c38, 0x10)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:340 +0x1a1
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).parseContext(0xc42037e000, 0xc420390300, 0xc420390380, 0x7, 0x8, 0xc400000030, 0x0, 0x30)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:169 +0x2f
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).ParseContext(0xc42037e000, 0xc420390380, 0x7, 0x8, 0xe, 0xc420382a00, 0xc420382a00)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:165 +0x4e
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc42037e000, 0xc420390380, 0x7, 0x8, 0xc420162a27, 0xd, 0x4, 0x8)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:185 +0x67
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.StartWithLog(0xc420143320, 0xd, 0xc420162a00, 0x35, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:293 +0x1639b
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.Start(0xc420143320, 0xd, 0xc420162a00, 0x35, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:48 +0x5b
proxy-web/server.autoRunCommand(0xc420143320, 0xd, 0xc420162a00, 0x35)
	/root/go/src/proxy-web/server/server.go:100 +0xc1
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 42 [runnable]:
proxy-web/server.autoRunCommand(0xc4201433a0, 0xd, 0xc420162a40, 0x35)
	/root/go/src/proxy-web/server/server.go:98
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 43 [runnable]:
os.(*File).Write(0xc42000e018, 0xc420358000, 0x36, 0x40, 0xebf0e0, 0x0, 0x0)
	/usr/lib/golang/src/os/file.go:136 +0x2fe
fmt.Fprintln(0xe5a0c0, 0xc42000e018, 0xc42021afa0, 0x1, 0x1, 0x1, 0xc42032a000, 0x0)
	/usr/lib/golang/src/fmt/print.go:248 +0x8b
fmt.Println(0xc42021afa0, 0x1, 0x1, 0xc42032a000, 0x0, 0x0)
	/usr/lib/golang/src/fmt/print.go:257 +0x57
proxy-web/server.autoRunCommand(0xc420143420, 0xd, 0xc420162a80, 0x35)
	/root/go/src/proxy-web/server/server.go:99 +0x95
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 44 [runnable]:
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.newFlagGroup(...)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/flags.go:17
proxy-web/vendor/gopkg.in/alecthomas/kingpin%2ev2.New(0xac96c9, 0x5, 0xad125a, 0x10, 0x0)
	/root/go/src/proxy-web/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:59 +0x154
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.StartWithLog(0xc4201434a0, 0xd, 0xc420162ac0, 0x35, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:76 +0x250
proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios.Start(0xc4201434a0, 0xd, 0xc420162ac0, 0x35, 0x0, 0x0)
	/root/go/src/proxy-web/vendor/github.com/snail007/goproxy/sdk/android-ios/sdk.go:48 +0x5b
proxy-web/server.autoRunCommand(0xc4201434a0, 0xd, 0xc420162ac0, 0x35)
	/root/go/src/proxy-web/server/server.go:100 +0xc1
created by proxy-web/server.AutoStart
	/root/go/src/proxy-web/server/server.go:94 +0x91

goroutine 45 [runnable]:
proxy-web/vendor/github.com/snail007/webtail.Serve.func1(0xc4202061e0, 0xc420145a40)
	/root/go/src/proxy-web/vendor/github.com/snail007/webtail/webtail.go:141
created by proxy-web/vendor/github.com/snail007/webtail.Serve
	/root/go/src/proxy-web/vendor/github.com/snail007/webtail/webtail.go:141 +0x206

**Comment by yincongcyincong** [comment]
这个问题是sdk那边多线程操作一个map所导致的，问题已经修复，下一版修复
