### ISSUE TITLE
老师，如何“添加代理” 求试用教程

### ISSUE THREAD

**Issue by becapital** [yincongcyincong/proxy-web#6]
1. 老师，如何“添加代理” 求详细配置教程+需要什么基本条件，比如我搭建了谷歌GAE有自己的APPID.....
2. 是不是需要自己的服务器搭建服务端？还是有搭建了谷歌GAE就可以？

小白一枚，谢谢

**Comment by yincongcyincong** [comment]
你需要在你的服务器上，比如谷歌云，也下载一个这种服务，然后启动，在端口48080上能看到界面
然后 命令那一栏填  http -t tls -p ":38080" -C proxy.crt -K proxy.key，加密文件最好用自己的
然后在你电脑本地也启动程序
命令：http -t tcp -p ":8080" -T tls -P "22.22.22.22:38080" -C proxy.crt -K proxy.key，22.22.22.22是你的谷歌云ip，两个加密文件要一样
之后你就能用本地的8080端口作为代理，进行上网了

**Comment by yincongcyincong** [comment]
https://github.com/snail007/goproxy/wiki/%E5%B0%8F%E7%99%BD%E5%BC%80%E5%BF%83%E4%B8%8A%E7%BD%91

这个是小白开心上网，你可以看一下
